"""
This family file was auto-generated by generate_family_file.py script.

Configuration parameters:
  url = https://bulbapedia.bulbagarden.net/w/api.php
  name = bulpedia

Please do not commit this to the Git repository!
"""
from pywikibot import family


class Family(family.Family):  # noqa: D101

    name = 'bulpedia'
    langs = {
        'en': 'bulbapedia.bulbagarden.net',
        'de': 'www.pokewiki.de',
        'es': 'www.wikidex.net',
        'fr': 'www.pokepedia.fr',
        'it': 'wiki.pokemoncentral.it',
        'ja': 'wiki.xn--rckteqa2e.com',
        'khw': 'www.khwiki.com',
        'zh': 'wiki.52poke.com',
    }

    def scriptpath(self, code):
        return {
            'en': '/w',
            'de': '',
            'es': '',
            'fr': '',
            'it': '',
            'ja': '/w',
            'khw': '',
            'zh': '',
        }[code]

    def protocol(self, code):
        return {
            'en': 'https',
            'de': 'https',
            'es': 'https',
            'fr': 'https',
            'it': 'https',
            'ja': 'https',
            'khw': 'https',
            'zh': 'https',
        }[code]
